// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API_Demo.Data;

#nullable disable

namespace Web_API_Demo.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_API_Demo.Model.Shirt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Colour = "Black",
                            Sex = "Female",
                            Size = 10
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Puma",
                            Colour = "Red",
                            Sex = "Male",
                            Size = 12
                        },
                        new
                        {
                            Id = 3,
                            Brand = "RHCP",
                            Colour = "Grey",
                            Sex = "Female",
                            Size = 10
                        },
                        new
                        {
                            Id = 4,
                            Brand = "TBK",
                            Colour = "Pink",
                            Sex = "Female",
                            Size = 6
                        },
                        new
                        {
                            Id = 5,
                            Brand = "TBS",
                            Colour = "Black",
                            Sex = "Male",
                            Size = 8
                        },
                        new
                        {
                            Id = 6,
                            Brand = "DC",
                            Colour = "White",
                            Sex = "Male",
                            Size = 11
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Adidas",
                            Colour = "Grey",
                            Sex = "Female",
                            Size = 10
                        },
                        new
                        {
                            Id = 8,
                            Brand = "[no-name]",
                            Colour = "White",
                            Sex = "Male",
                            Size = 12
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Nike",
                            Colour = "Gold",
                            Sex = "Female",
                            Size = 10
                        },
                        new
                        {
                            Id = 10,
                            Brand = "RHCP",
                            Colour = "Red",
                            Sex = "Female",
                            Size = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
